### ISSUE TITLE
Failed to compile the project

### ISSUE THREAD

**Issue by gkitambala** [sukesh-ak/LVGL8-WT32-SC01-IDF#1]
Hey!
 Thanks for this amazing project. I have the same hardware as specified but when I try to run the commmand idf.py menuconfig I get the error:

CMake Error at C:/Users/gkitambala/esp/esp-idf/tools/cmake/build.cmake:201 (message):
  Failed to resolve component 'LovyanGFX'.
Call Stack (most recent call first):
  C:/Users/gkitambala/esp/esp-idf/tools/cmake/build.cmake:227 (__build_resolve_and_add_req)
  C:/Users/gkitambala/esp/esp-idf/tools/cmake/build.cmake:509 (__build_expand_requirements)
  C:/Users/gkitambala/esp/esp-idf/tools/cmake/project.cmake:384 (idf_build_process)
  CMakeLists.txt:6 (project)

Please tell me how to resolve this.
Thanks

**Comment by sukesh-ak** [comment]
@gkitambala 
After clone command switch to the project folder and try

git submodule update --init --recursive

**Comment by sukesh-ak** [comment]
You can also check this updated sample as well for IDF. 

https://github.com/sukesh-ak/LVGL8x-SDSPI-Template

**Comment by gkitambala** [comment]
This has worked. Thank you @sukesh-ak.

**Comment by sukesh-ak** [comment]
@gkitambala Don't forget to check the updated sample
https://github.com/sukesh-ak/ESP32-TUX
